[package]
name = "natsuki"
version = "3.0.4"
authors = [
    "Chen-Pang He (https://jdh8.org)",
    "u/YourWrstNightmare (https://www.reddit.com/user/YourWrstNightmare)",
    "u/RoseQuartz6758 (https://www.reddit.com/user/RoseQuartz6758)",
]
edition = "2021"
description = "Discord bot named after Natsuki from Doki Doki Literature Club"
repository = "https://github.com/jdh8/natsuki"
license = "MIT"
categories = ["games"]
keywords = ["discord", "ddlc"]

[dependencies]
anyhow = "1.0.75"
base64 = "0.22.1"
bitflags = "2.4.0"
chrono = "0.4.30"
command_attr = "0.5.1"
csscolorparser = "0.6.2"
futures = "0.3.28"
image = "0.25.0"
md5 = "0.7.0"
poise = { version = "0.6.1", features = ["collector"] }
rand = "0.8.5"
regex = "1.9.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.105"
shuttle-runtime = "0.44.0"
shuttle-serenity = "0.44.0"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
topgg = { version = "1.4.1", features = ["autoposter", "serenity-cached"] }
tree_magic_mini = "3.0.3"
webp = "0.3.0"
